language: go
services:
  - mongodb
go:
  - master
install:
  - go get .
  - go get github.com/smartystreets/goconvey
  - go get go.mongodb.org/mongo-driver/bson
  - go get go.mongodb.org/mongo-driver/mongo
  - go get github.com/sirupsen/logrus
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci